### PR TITLE
(doc) update README for install with source

### PR DESCRIPTION
**Pull request by wnz27**
I found the repo relase name is already changed
截屏2022-05-12 10 36 52
so may be fix the cmd

### CODE REVIEW

**Comment by kl7sn** [comment]
Mogo was the name of the project before, and the current v0.3.0 has been changed to ClickVisual. 

https://github.com/clickvisual/clickvisual/releases/tag/v0.3.0-rc1

During this time we produced some documented errors, tks for your PR

**Comment by wnz27** [comment]
> Mogo was the name of the project before, and the current v0.3.0 has been changed to ClickVisual.
> 
> https://github.com/clickvisual/clickvisual/releases/tag/v0.3.0-rc1
> 
> During this time we produced some documented errors, tks for your PR

u're welcome, one more question: may be don't support Mac OS with m1?

**Comment by kl7sn** [comment]
I ran into the same problem when testing locally.I will fix the problem as soon as possible.

> qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by wnz27** [comment]
> I ran into the same problem when testing locally.I will fix the problem as soon as possible.
> 
> > qemu: uncaught target signal 11 (Segmentation fault) - core dumped

u replay me? thank u ~ I close this pr? or u do it?

**Comment by kl7sn** [comment]
> > I ran into the same problem when testing locally.I will fix the problem as soon as possible.
> > > qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> 
> u replay me? thank u ~ I close this pr? or u do it?

i will do it, looking forward to more communication in the future.

**Pull request closed without merging**
